# Dependabot configuration for automated dependency updates
version: 2
updates:
  # Node.js dependencies for Manager
  - package-ecosystem: "npm"
    directory: "/manager"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "@your-github-username"
    labels:
      - "dependencies"
      - "manager"

  # Go modules for Nodes
  - package-ecosystem: "gomod"
    directory: "/nodes"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "@your-github-username"
    labels:
      - "dependencies"
      - "nodes"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"