name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

permissions:
  contents: read
  packages: write
  security-events: write
  actions: read

env:
  GO_VERSION: '>=1.25.1'
  NODE_VERSION: '24'

jobs:
  # Security scanning job
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v5

      - name: Run Trivy security scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  # Build and test Manager (Node.js)
  build-manager:
    name: Build Manager
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./manager

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: manager/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npx eslint . --ext .js --ignore-path .gitignore || true

      - name: Check for vulnerabilities
        run: npm audit --audit-level=high || true

      - name: Build
        run: |
          echo "No build step required for Express app"
          echo "Checking if server starts..."
          timeout 5 npm start || true

  # Build and test Nodes (Go)
  build-nodes:
    name: Build Nodes
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./nodes
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          working-directory: ./nodes

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./... || true

      - name: Build binary
        run: |
          go build -v -o agent${{ matrix.os == 'windows-latest' && '.exe' || '' }} .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: agent-${{ matrix.os }}
          path: nodes/agent${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  # Create release when tag is pushed
  create-release:
    name: Create Release
    needs: [security-scan, build-manager, build-nodes]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - uses: actions/checkout@v5

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Extract release notes
        id: get_notes
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}

          # Extract section for this version from RELEASE_NOTES.md
          # Use sed to find the version heading and extract until the next ## heading
          sed -n "/^## ${VERSION}\$/,/^## /p" RELEASE_NOTES.md | sed '$d' > release_notes.txt

          # Remove the version heading line itself
          sed -i '1d' release_notes.txt

          # Check if we got any content
          if [ ! -s release_notes.txt ]; then
            echo "ERROR: No release notes found for version $VERSION in RELEASE_NOTES.md"
            cat RELEASE_NOTES.md
            exit 1
          fi

          echo "NOTES_FILE=release_notes.txt" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          gh release create "$VERSION" \
            --title "$VERSION" \
            --notes-file release_notes.txt \
            --latest

  # Release job - uploads assets to existing release
  release:
    name: Upload Release Assets
    needs: [create-release]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./artifacts

      - name: Create release archives
        run: |
          # Extract version from tag (e.g., refs/tags/v0.11.10 -> v0.11.10)
          VERSION="${GITHUB_REF#refs/tags/}"

          # Package Manager
          cd manager
          tar -czf ../manager-${VERSION}.tar.gz --exclude=node_modules --exclude=data .
          cd ..

          # Package each agent binary
          for dir in artifacts/agent-*; do
            platform=$(basename $dir | sed 's/agent-//')
            cd $dir
            if [[ "$platform" == "windows-latest" ]]; then
              zip ../../agent-windows-${VERSION}.zip agent.exe
              # Also create unversioned name for 'latest' downloads
              cp ../../agent-windows-${VERSION}.zip ../../agent-windows.zip
            elif [[ "$platform" == "macos-latest" ]]; then
              tar -czf ../../agent-macos-${VERSION}.tar.gz agent
              # Also create unversioned name for 'latest' downloads
              cp ../../agent-macos-${VERSION}.tar.gz ../../agent-macos.tar.gz
            else
              tar -czf ../../agent-linux-${VERSION}.tar.gz agent
              # Also create unversioned name for 'latest' downloads
              cp ../../agent-linux-${VERSION}.tar.gz ../../agent-linux.tar.gz
            fi
            cd ../..
          done

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            manager-*.tar.gz
            agent-linux-*.tar.gz
            agent-linux.tar.gz
            agent-windows-*.zip
            agent-windows.zip
            agent-macos-*.tar.gz
            agent-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Docker build and push to GitHub Container Registry
  docker:
    name: Docker Build
    needs: [build-manager, build-nodes]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/controlcenter-manager
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Manager Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./manager
          file: ./manager/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/controlcenter-manager:latest
            ghcr.io/${{ github.repository_owner }}/controlcenter-manager:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.description=Control Center Manager - Web UI and API
            org.opencontainers.image.licenses=AGPL-3.0
        continue-on-error: true

      - name: Build and push Agent Docker image (for Kubernetes)
        uses: docker/build-push-action@v6
        with:
          context: ./nodes
          file: ./nodes/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/controlcenter-nodes:latest
            ghcr.io/${{ github.repository_owner }}/controlcenter-nodes:k8s-${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.description=Control Center Agent - For Kubernetes/Testing only
            org.opencontainers.image.licenses=AGPL-3.0
        continue-on-error: true